import os

def help():
  print()
  print('{:^120s}'.format("*"*120))
  print('{:^120s}'.format("MENU UMUM"))
  print('{:^120s}'.format("*"*120))
  print("help - Petunjuk Game")
  print("list_game_toko - Listing Game di Toko Berdasarkan ID, Tahun Rilis, atau Harga")
  print("search_game_toko - Mencari Game di Toko dari ID, Nama Game, Harga, Kategori dan Tahun Rilis")
  print("tictactoe - Bermain Game tic-tac-toe")
  print("kerangajaib - Bermain bersama Kerang Ajaib")
  print("save - Menyimpan File")
  print("exit - Keluar dari BNMO")
  print()
  print()
  print('{:^120s}'.format("*"*120))
  print('{:^120s}'.format("MENU USER"))
  print('{:^120s}'.format("*"*120))
  print("beli_game - Memebeli Game di Toko")
  print("list_game - Melihat Game yang Dimiliki")
  print("search_my_game - Mencari Game Berdasarkan ID Game dan Tahun Rilis")
  print("riwayat - Melihat Riwayat Pembelian Game")
  print()
  print()
  print('{:^120s}'.format("*"*120))
  print('{:^120s}'.format("MENU ADMIN"))
  print('{:^120s}'.format("*"*120))
  print("register - Registrasi ke dalam BNMO")
  print("tambah_game - Menambah Game ke Toko Game")
  print("ubah_game - Mengubah Game pada Toko Game")
  print("ubah_stok - Mengubah Stok Game di Toko")
  print("topup - Top Up Saldo")
  print()
  print()